notifications:
  email: true

dist: focal

language: node_js
node_js: node

cache: npm

addons:
  ssh_known_hosts: 165.22.87.194

script:
  - cd ./application
  - npm install
  - npm run build
  - cd ..

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  provider: script
  skip-cleanup: true
  script: scp -r ./application/build/* $REMOTE_USER@165.22.87.194:/var/www/$REMOTE_LOCATION
  on:
    branch: master
